#!/bin/sh
set -e

. /usr/share/debconf/confmodule

db_version 2.0 || true

db_input high case-organizer/smtp-host || true
db_input high case-organizer/smtp-port || true
db_input high case-organizer/smtp-username || true
db_input high case-organizer/smtp-password || true
db_input high case-organizer/smtp-use-tls || true
db_go || true

exit 0
